### ISSUE TITLE
ablation study setting

### ISSUE THREAD

**Issue by valencebond** [iCVTEAM/TDRG#2]
thanks for your detailed codes. I wonder about the ablation study settings of Fig.3 . Since SGD optimizer largely depends on the scale of the loss, is it necessary to multiple a single loss (for example, trans loss) by four to match the initial loss scale when I want to validate the effect of trans loss?

**Comment by JiaweiZhao-git** [comment]
Generally speaking, there is no need to match the loss scale for the ablation study.
