### ISSUE TITLE
Visualization script is missing

### ISSUE THREAD

**Issue by monjoybme** [iCVTEAM/TDRG#5]
Hi,

Awesome work! I'm curious to know if you can share the activation map or visualization script.

**Comment by JiaweiZhao-git** [comment]
Unfortunately, the visualization script is missing, you can re-implement it with [Grad-CAM ](https://github.com/jacobgil/pytorch-grad-cam).

**Comment by monjoybme** [comment]
@JiaweiZhao-git Thanks solved this issue.
